title: Formsflow.ai
description: formsflow.ai
theme: just-the-docs

url: https://aot-technologies.github.io/forms-flow-ai-doc

# Set a path/url to a logo that will be displayed instead of the title
logo: "./assets/logo.svg"

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "./assets/logo.svg"

# aux_links: # remove if you don't want this link to appear on your pages
#   Template Repository: https://aot-technologies.github.io/formsflow.ai

  # Enable or disable the site search
# Supports true (default) or false
# search_enabled: false

# Aux links for the upper right navigation
# aux_links:
#   "Docker":
#     - "https://github.com/AOT-Technologies/forms-flow-ai"

# color_scheme: dark
# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"
